FROM mcr.microsoft.com/powershell:latest
 
# Install git
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
 
# Create a non-root user (VSC default practice)
ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME
 
# Set working directory
WORKDIR /workspace
